// <auto-generated />
namespace PPVR.WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterOcorrenciaRemoveColumnVerificada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterOcorrenciaRemoveColumnVerificada));
        
        string IMigrationMetadata.Id
        {
            get { return "201611010012493_AlterOcorrenciaRemoveColumnVerificada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
