//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        internal static string Acoes {
            get {
                return ResourceManager.GetString("Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo?.
        /// </summary>
        internal static string Ativo {
            get {
                return ResourceManager.GetString("Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string CandidatoNome {
            get {
                return ResourceManager.GetString("CandidatoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Urna.
        /// </summary>
        internal static string CandidatoNomeUrna {
            get {
                return ResourceManager.GetString("CandidatoNomeUrna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Eleitoral.
        /// </summary>
        internal static string CandidatoNumeroEleitoral {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar pelo nome do candidato, nome da urna ou número eleitoral....
        /// </summary>
        internal static string CandidatoPesquisarPlaceholder {
            get {
                return ResourceManager.GetString("CandidatoPesquisarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidatos.
        /// </summary>
        internal static string Candidatos {
            get {
                return ResourceManager.GetString("Candidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidatos encontrados.
        /// </summary>
        internal static string CandidatoTotalPartidos {
            get {
                return ResourceManager.GetString("CandidatoTotalPartidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Criação.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitar.
        /// </summary>
        internal static string Desabilitar {
            get {
                return ResourceManager.GetString("Desabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string PartidoNome {
            get {
                return ResourceManager.GetString("PartidoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Eleitoral.
        /// </summary>
        internal static string PartidoNumeroEleitoral {
            get {
                return ResourceManager.GetString("PartidoNumeroEleitoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar pelo nome do partido, sigla ou número eleitoral....
        /// </summary>
        internal static string PartidoPesquisarPlaceholder {
            get {
                return ResourceManager.GetString("PartidoPesquisarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidos.
        /// </summary>
        internal static string Partidos {
            get {
                return ResourceManager.GetString("Partidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla.
        /// </summary>
        internal static string PartidoSigla {
            get {
                return ResourceManager.GetString("PartidoSigla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Candidatos.
        /// </summary>
        internal static string PartidoTitleListaCandidatos {
            get {
                return ResourceManager.GetString("PartidoTitleListaCandidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Partidos Políticos.
        /// </summary>
        internal static string PartidoTitleListaPartidosPoliticos {
            get {
                return ResourceManager.GetString("PartidoTitleListaPartidosPoliticos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidos encontrados.
        /// </summary>
        internal static string PartidoTotalPartidos {
            get {
                return ResourceManager.GetString("PartidoTotalPartidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        internal static string Pesquisar {
            get {
                return ResourceManager.GetString("Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Atualização.
        /// </summary>
        internal static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        internal static string Visualizar {
            get {
                return ResourceManager.GetString("Visualizar", resourceCulture);
            }
        }
    }
}
