//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ValidationErrorMessage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Candidato deve ter no máximo 60 caracteres..
        /// </summary>
        internal static string CandidatoNomeInvalidLength {
            get {
                return ResourceManager.GetString("CandidatoNomeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Candidato não pode ser nulo..
        /// </summary>
        internal static string CandidatoNomeNotNull {
            get {
                return ResourceManager.GetString("CandidatoNomeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Deputado Estadual não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralDeputadoEstadualInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralDeputadoEstadualInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Deputado Federal não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralDeputadoFederalInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralDeputadoFederalInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Governador não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralGovernadorInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralGovernadorInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Prefeito não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralPrefeitoInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralPrefeitoInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Presidência não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralPresidenteInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralPresidenteInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Senador não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralSenadorInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralSenadorInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Vereador não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralVereadorInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralVereadorInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Descrição do Cargo Eletivo deve ter entre 1 e 255 caracteres..
        /// </summary>
        internal static string CargoEletivoDescricaoInvalidLength {
            get {
                return ResourceManager.GetString("CargoEletivoDescricaoInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Cargo Eletivo deve ter entre 1 e 30 caracteres..
        /// </summary>
        internal static string CargoEletivoNomeInvalidLength {
            get {
                return ResourceManager.GetString("CargoEletivoNomeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Cargo Letivo não pode ser nulo..
        /// </summary>
        internal static string CargoEletivoNomeNotNull {
            get {
                return ResourceManager.GetString("CargoEletivoNomeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Bairro deve ter entre 1 e 60 caracteres..
        /// </summary>
        internal static string EnderecoBairroInvalidLength {
            get {
                return ResourceManager.GetString("EnderecoBairroInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP informado não é válido..
        /// </summary>
        internal static string EnderecoCEPInvalidLength {
            get {
                return ResourceManager.GetString("EnderecoCEPInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome da Cidade deve ter entre 1 e 60 caracteres..
        /// </summary>
        internal static string EnderecoCidadeInvalidLength {
            get {
                return ResourceManager.GetString("EnderecoCidadeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Estado informado não existe..
        /// </summary>
        internal static string EnderecoEstadoInvalidValue {
            get {
                return ResourceManager.GetString("EnderecoEstadoInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Endereço Formatado deve ter entre 1 e 255 caracteres..
        /// </summary>
        internal static string EnderecoFormatadoInvalidLength {
            get {
                return ResourceManager.GetString("EnderecoFormatadoInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Descrição do Espectro Político deve ter no máximo 255 caracteres..
        /// </summary>
        internal static string EspectroPoliticoDescricaoInvalidLength {
            get {
                return ResourceManager.GetString("EspectroPoliticoDescricaoInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome da Espectro Político deve ter entre 1 e 30 caracteres..
        /// </summary>
        internal static string EspectroPoliticoNomeInvalidLength {
            get {
                return ResourceManager.GetString("EspectroPoliticoNomeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Espectro Político não pode ser nulo..
        /// </summary>
        internal static string EspectroPoliticoNomeNotNull {
            get {
                return ResourceManager.GetString("EspectroPoliticoNomeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A foto não possui as informações de geolocalização..
        /// </summary>
        internal static string ExifTagsGeolocationNull {
            get {
                return ResourceManager.GetString("ExifTagsGeolocationNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome da Ideologia deve ter entre 1 e 30 caracteres..
        /// </summary>
        internal static string IdeologiaNomeInvalidLength {
            get {
                return ResourceManager.GetString("IdeologiaNomeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome da Ideologia não pode ser nulo..
        /// </summary>
        internal static string IdeologiaNomeNotNull {
            get {
                return ResourceManager.GetString("IdeologiaNomeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Espectro Político informado não existe..
        /// </summary>
        internal static string PartidoEspectroPoliticoInvalidValue {
            get {
                return ResourceManager.GetString("PartidoEspectroPoliticoInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Partido deve ter entre 1 e 60 caracteres..
        /// </summary>
        internal static string PartidoNomeInvalidLength {
            get {
                return ResourceManager.GetString("PartidoNomeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Partido não pode ser nulo..
        /// </summary>
        internal static string PartidoNomeNotNull {
            get {
                return ResourceManager.GetString("PartidoNomeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Partido não é válido..
        /// </summary>
        internal static string PartidoNumeroEleitoralInvalidRange {
            get {
                return ResourceManager.GetString("PartidoNumeroEleitoralInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Sigla do Partido deve ter entre 1 e 10 caracteres..
        /// </summary>
        internal static string PartidoSiglaInvalidLength {
            get {
                return ResourceManager.GetString("PartidoSiglaInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Sigla do Partido não pode ser nula..
        /// </summary>
        internal static string PartidoSiglaNotNull {
            get {
                return ResourceManager.GetString("PartidoSiglaNotNull", resourceCulture);
            }
        }
    }
}
