//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPVR.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPVR.WebApp.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Acoes {
            get {
                return ResourceManager.GetString("Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPVR.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPVR - .
        /// </summary>
        public static string AppNameFull {
            get {
                return ResourceManager.GetString("AppNameFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo?.
        /// </summary>
        public static string Ativo {
            get {
                return ResourceManager.GetString("Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Obrigatório.
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string CandidatoNome {
            get {
                return ResourceManager.GetString("CandidatoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Urna.
        /// </summary>
        public static string CandidatoNomeUrna {
            get {
                return ResourceManager.GetString("CandidatoNomeUrna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Eleitoral.
        /// </summary>
        public static string CandidatoNumeroEleitoral {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar pelo nome do candidato, nome da urna ou número eleitoral....
        /// </summary>
        public static string CandidatoPesquisarPlaceholder {
            get {
                return ResourceManager.GetString("CandidatoPesquisarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidatos.
        /// </summary>
        public static string Candidatos {
            get {
                return ResourceManager.GetString("Candidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Candidatos.
        /// </summary>
        public static string CandidatoTitleListaCandidatos {
            get {
                return ResourceManager.GetString("CandidatoTitleListaCandidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidatos encontrados.
        /// </summary>
        public static string CandidatoTotalPartidos {
            get {
                return ResourceManager.GetString("CandidatoTotalPartidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Criação.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        public static string Criar {
            get {
                return ResourceManager.GetString("Criar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desabilitar.
        /// </summary>
        public static string Desabilitar {
            get {
                return ResourceManager.GetString("Desabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideologia.
        /// </summary>
        public static string Ideologia {
            get {
                return ResourceManager.GetString("Ideologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Ideologia.
        /// </summary>
        public static string IdeologiaAdicionar {
            get {
                return ResourceManager.GetString("IdeologiaAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Ideologia.
        /// </summary>
        public static string IdeologiaDetalhes {
            get {
                return ResourceManager.GetString("IdeologiaDetalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Ideologia.
        /// </summary>
        public static string IdeologiaEditar {
            get {
                return ResourceManager.GetString("IdeologiaEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe nenhum partido associado a ideologia..
        /// </summary>
        public static string IdeologiaNenhumPartidoAssociado {
            get {
                return ResourceManager.GetString("IdeologiaNenhumPartidoAssociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string IdeologiaNome {
            get {
                return ResourceManager.GetString("IdeologiaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o nome da ideologia..
        /// </summary>
        public static string IdeologiaNomePlaceholder {
            get {
                return ResourceManager.GetString("IdeologiaNomePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar pelo nome da ideologia....
        /// </summary>
        public static string IdeologiaPesquisarPlaceholder {
            get {
                return ResourceManager.GetString("IdeologiaPesquisarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtde. de Partidos Associados.
        /// </summary>
        public static string IdeologiaQtdePartidosAssociados {
            get {
                return ResourceManager.GetString("IdeologiaQtdePartidosAssociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideologias.
        /// </summary>
        public static string Ideologias {
            get {
                return ResourceManager.GetString("Ideologias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Ideologias.
        /// </summary>
        public static string IdeologiaTitleListaIdeologias {
            get {
                return ResourceManager.GetString("IdeologiaTitleListaIdeologias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideologias encontradas.
        /// </summary>
        public static string IdeologiaTotalIdeologias {
            get {
                return ResourceManager.GetString("IdeologiaTotalIdeologias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string PartidoNome {
            get {
                return ResourceManager.GetString("PartidoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Eleitoral.
        /// </summary>
        public static string PartidoNumeroEleitoral {
            get {
                return ResourceManager.GetString("PartidoNumeroEleitoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar pelo nome do partido, sigla ou número eleitoral....
        /// </summary>
        public static string PartidoPesquisarPlaceholder {
            get {
                return ResourceManager.GetString("PartidoPesquisarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidos.
        /// </summary>
        public static string Partidos {
            get {
                return ResourceManager.GetString("Partidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla.
        /// </summary>
        public static string PartidoSigla {
            get {
                return ResourceManager.GetString("PartidoSigla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Partidos Políticos.
        /// </summary>
        public static string PartidoTitleListaPartidosPoliticos {
            get {
                return ResourceManager.GetString("PartidoTitleListaPartidosPoliticos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidos encontrados.
        /// </summary>
        public static string PartidoTotalPartidos {
            get {
                return ResourceManager.GetString("PartidoTotalPartidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string Pesquisar {
            get {
                return ResourceManager.GetString("Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        public static string Sobre {
            get {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Atualização.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        public static string Visualizar {
            get {
                return ResourceManager.GetString("Visualizar", resourceCulture);
            }
        }
    }
}
