//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPVR.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPVR.WebApp.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Acoes {
            get {
                return ResourceManager.GetString("Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo?.
        /// </summary>
        public static string Ativo {
            get {
                return ResourceManager.GetString("Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Obrigatório.
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidato.
        /// </summary>
        public static string Candidato {
            get {
                return ResourceManager.GetString("Candidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe nenhuma ocorrência registrada para este candidato..
        /// </summary>
        public static string CandidatoNenhumRegistroOcorrencia {
            get {
                return ResourceManager.GetString("CandidatoNenhumRegistroOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string CandidatoNome {
            get {
                return ResourceManager.GetString("CandidatoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Urna.
        /// </summary>
        public static string CandidatoNomeUrna {
            get {
                return ResourceManager.GetString("CandidatoNomeUrna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Eleitoral.
        /// </summary>
        public static string CandidatoNumeroEleitoral {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar pelo nome da urna do candidato ou número eleitoral....
        /// </summary>
        public static string CandidatoPesquisarPlaceholder {
            get {
                return ResourceManager.GetString("CandidatoPesquisarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidatos.
        /// </summary>
        public static string Candidatos {
            get {
                return ResourceManager.GetString("Candidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Candidatos.
        /// </summary>
        public static string CandidatoTitleListaCandidatos {
            get {
                return ResourceManager.GetString("CandidatoTitleListaCandidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade Eleitoral.
        /// </summary>
        public static string CandidatoUnidadeEleitoral {
            get {
                return ResourceManager.GetString("CandidatoUnidadeEleitoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade Federação.
        /// </summary>
        public static string CandidatoUnidadeFederacao {
            get {
                return ResourceManager.GetString("CandidatoUnidadeFederacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro-direita à Direita.
        /// </summary>
        public static string CentroDireitaADireita {
            get {
                return ResourceManager.GetString("CentroDireitaADireita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2016 - PPVR (Propaganda Política e seu Valor Real).
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Criação.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar uma conta.
        /// </summary>
        public static string CriarConta {
            get {
                return ResourceManager.GetString("CriarConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleição.
        /// </summary>
        public static string Eleicao {
            get {
                return ResourceManager.GetString("Eleicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string EleicaoAno {
            get {
                return ResourceManager.GetString("EleicaoAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string EleicaoDescricao {
            get {
                return ResourceManager.GetString("EleicaoDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turno.
        /// </summary>
        public static string EleicaoTurno {
            get {
                return ResourceManager.GetString("EleicaoTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleições.
        /// </summary>
        public static string Eleicoes {
            get {
                return ResourceManager.GetString("Eleicoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar pela descrição da eleição....
        /// </summary>
        public static string EleicoesPesquisarPlaceholder {
            get {
                return ResourceManager.GetString("EleicoesPesquisarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Foto.
        /// </summary>
        public static string EnviarFoto {
            get {
                return ResourceManager.GetString("EnviarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espectro Político.
        /// </summary>
        public static string EspectroPolitico {
            get {
                return ResourceManager.GetString("EspectroPolitico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro.
        /// </summary>
        public static string EspectroPoliticoCentro {
            get {
                return ResourceManager.GetString("EspectroPoliticoCentro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro-direita.
        /// </summary>
        public static string EspectroPoliticoCentroDireita {
            get {
                return ResourceManager.GetString("EspectroPoliticoCentroDireita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro-direita à Direita.
        /// </summary>
        public static string EspectroPoliticoCentroDireitaADireita {
            get {
                return ResourceManager.GetString("EspectroPoliticoCentroDireitaADireita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro-direita.
        /// </summary>
        public static string EspectroPoliticoCentroEsquerda {
            get {
                return ResourceManager.GetString("EspectroPoliticoCentroEsquerda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro-esquerda à Esquerda.
        /// </summary>
        public static string EspectroPoliticoCentroEsquerdaAEsquerda {
            get {
                return ResourceManager.GetString("EspectroPoliticoCentroEsquerdaAEsquerda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direita.
        /// </summary>
        public static string EspectroPoliticoDireita {
            get {
                return ResourceManager.GetString("EspectroPoliticoDireita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direita à Extrema-direita.
        /// </summary>
        public static string EspectroPoliticoDireitaAExtremaDireita {
            get {
                return ResourceManager.GetString("EspectroPoliticoDireitaAExtremaDireita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esquerda.
        /// </summary>
        public static string EspectroPoliticoEsquerda {
            get {
                return ResourceManager.GetString("EspectroPoliticoEsquerda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esquerda à Extrema-esquerda.
        /// </summary>
        public static string EspectroPoliticoEsquerdaAExtremaEsquerda {
            get {
                return ResourceManager.GetString("EspectroPoliticoEsquerdaAExtremaEsquerda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrema-direita.
        /// </summary>
        public static string EspectroPoliticoExtremaDireita {
            get {
                return ResourceManager.GetString("EspectroPoliticoExtremaDireita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrema-esquerda.
        /// </summary>
        public static string EspectroPoliticoExtremaEsquerda {
            get {
                return ResourceManager.GetString("EspectroPoliticoExtremaEsquerda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto salva. Candidatos encontrados:.
        /// </summary>
        public static string FotoSalvaCandidatosEncontrados {
            get {
                return ResourceManager.GetString("FotoSalvaCandidatosEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A foto foi salva, porém nenhum candidato foi encontrado..
        /// </summary>
        public static string FotoSalvaNenhumCandidatoEncontrado {
            get {
                return ResourceManager.GetString("FotoSalvaNenhumCandidatoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideologia.
        /// </summary>
        public static string Ideologia {
            get {
                return ResourceManager.GetString("Ideologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe nenhum partido associado a ideologia..
        /// </summary>
        public static string IdeologiaNenhumPartidoAssociado {
            get {
                return ResourceManager.GetString("IdeologiaNenhumPartidoAssociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string IdeologiaNome {
            get {
                return ResourceManager.GetString("IdeologiaNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o nome da ideologia..
        /// </summary>
        public static string IdeologiaNomePlaceholder {
            get {
                return ResourceManager.GetString("IdeologiaNomePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar pelo nome da ideologia....
        /// </summary>
        public static string IdeologiaPesquisarPlaceholder {
            get {
                return ResourceManager.GetString("IdeologiaPesquisarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtde. Partidos Associados.
        /// </summary>
        public static string IdeologiaQtdePartidosAssociados {
            get {
                return ResourceManager.GetString("IdeologiaQtdePartidosAssociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideologias.
        /// </summary>
        public static string Ideologias {
            get {
                return ResourceManager.GetString("Ideologias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Ideologias.
        /// </summary>
        public static string IdeologiaTitleListaIdeologias {
            get {
                return ResourceManager.GetString("IdeologiaTitleListaIdeologias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar.
        /// </summary>
        public static string Lembrar {
            get {
                return ResourceManager.GetString("Lembrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Candidatos.
        /// </summary>
        public static string ListaCandidatos {
            get {
                return ResourceManager.GetString("ListaCandidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Eleições.
        /// </summary>
        public static string ListaEleicoes {
            get {
                return ResourceManager.GetString("ListaEleicoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Ideologias.
        /// </summary>
        public static string ListaIdeologias {
            get {
                return ResourceManager.GetString("ListaIdeologias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Ideologias que estão Associadas ao Partido.
        /// </summary>
        public static string ListaIdeologiasAssociadasPartido {
            get {
                return ResourceManager.GetString("ListaIdeologiasAssociadasPartido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Partidos.
        /// </summary>
        public static string ListaPartidos {
            get {
                return ResourceManager.GetString("ListaPartidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Partidos que estão Associados a Ideologia.
        /// </summary>
        public static string ListaPartidosAssociadosIdeologia {
            get {
                return ResourceManager.GetString("ListaPartidosAssociadosIdeologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Tipos de Propaganda.
        /// </summary>
        public static string ListaTiposPropaganda {
            get {
                return ResourceManager.GetString("ListaTiposPropaganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partido.
        /// </summary>
        public static string Partido {
            get {
                return ResourceManager.GetString("Partido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espectro Político.
        /// </summary>
        public static string PartidoEspectroPolitico {
            get {
                return ResourceManager.GetString("PartidoEspectroPolitico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o espectro político do partido..
        /// </summary>
        public static string PartidoEspectroPoliticoPlaceholder {
            get {
                return ResourceManager.GetString("PartidoEspectroPoliticoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string PartidoNome {
            get {
                return ResourceManager.GetString("PartidoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o nome do partido..
        /// </summary>
        public static string PartidoNomePlaceholder {
            get {
                return ResourceManager.GetString("PartidoNomePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Eleitoral.
        /// </summary>
        public static string PartidoNumeroEleitoral {
            get {
                return ResourceManager.GetString("PartidoNumeroEleitoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o número eleitoral do partido..
        /// </summary>
        public static string PartidoNumeroEleitoralPlaceholder {
            get {
                return ResourceManager.GetString("PartidoNumeroEleitoralPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar pelo nome do partido, sigla ou número eleitoral....
        /// </summary>
        public static string PartidoPesquisarPlaceholder {
            get {
                return ResourceManager.GetString("PartidoPesquisarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtde. Candidatos Associados.
        /// </summary>
        public static string PartidoQtdeCandidatosAssociados {
            get {
                return ResourceManager.GetString("PartidoQtdeCandidatosAssociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidos.
        /// </summary>
        public static string Partidos {
            get {
                return ResourceManager.GetString("Partidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla.
        /// </summary>
        public static string PartidoSigla {
            get {
                return ResourceManager.GetString("PartidoSigla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a sigla do partido..
        /// </summary>
        public static string PartidoSiglaPlaceholder {
            get {
                return ResourceManager.GetString("PartidoSiglaPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Partidos Políticos.
        /// </summary>
        public static string PartidoTitleListaPartidosPoliticos {
            get {
                return ResourceManager.GetString("PartidoTitleListaPartidosPoliticos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidos encontrados.
        /// </summary>
        public static string PartidoTotalPartidos {
            get {
                return ResourceManager.GetString("PartidoTotalPartidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        public static string Pesquisar {
            get {
                return ResourceManager.GetString("Pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPVR.
        /// </summary>
        public static string PPVR {
            get {
                return ResourceManager.GetString("PPVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propaganda Política e seu Valor Real.
        /// </summary>
        public static string PropagandaPolíticaValorReal {
            get {
                return ResourceManager.GetString("PropagandaPolíticaValorReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtde. Ocorrências.
        /// </summary>
        public static string QtdeOcorrencias {
            get {
                return ResourceManager.GetString("QtdeOcorrencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorrências por Tipo de Propaganda.
        /// </summary>
        public static string RelatorioOcorrenciasTipoPropaganda {
            get {
                return ResourceManager.GetString("RelatorioOcorrenciasTipoPropaganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatórios.
        /// </summary>
        public static string Relatorios {
            get {
                return ResourceManager.GetString("Relatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores Gastos por Tipo de Ocorrência.
        /// </summary>
        public static string RelatorioValoresGastosTipoOcorrencia {
            get {
                return ResourceManager.GetString("RelatorioValoresGastosTipoOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar senha.
        /// </summary>
        public static string SenhaConfirmar {
            get {
                return ResourceManager.GetString("SenhaConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        public static string Sobre {
            get {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Propaganda.
        /// </summary>
        public static string TipoPropaganda {
            get {
                return ResourceManager.GetString("TipoPropaganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string TipoPropagandaDescricao {
            get {
                return ResourceManager.GetString("TipoPropagandaDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a descrição do tipo da propaganda..
        /// </summary>
        public static string TipoPropagandaDescricaoPlaceholder {
            get {
                return ResourceManager.GetString("TipoPropagandaDescricaoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o tipo da propaganda.
        /// </summary>
        public static string TipoPropagandaSelecionar {
            get {
                return ResourceManager.GetString("TipoPropagandaSelecionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Médio.
        /// </summary>
        public static string TipoPropagandaValorMedio {
            get {
                return ResourceManager.GetString("TipoPropagandaValorMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o valor médio do tipo da propaganda..
        /// </summary>
        public static string TipoPropagandaValorMedioPlaceholder {
            get {
                return ResourceManager.GetString("TipoPropagandaValorMedioPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Propaganda.
        /// </summary>
        public static string TiposPropaganda {
            get {
                return ResourceManager.GetString("TiposPropaganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar pela descrição do tipo da propaganda....
        /// </summary>
        public static string TiposPropagandaPesquisarPlaceholder {
            get {
                return ResourceManager.GetString("TiposPropagandaPesquisarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de .
        /// </summary>
        public static string TotalDe {
            get {
                return ResourceManager.GetString("TotalDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Gasto.
        /// </summary>
        public static string TotalGasto {
            get {
                return ResourceManager.GetString("TotalGasto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Atualização.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a senha informada..
        /// </summary>
        public static string UsuarioConfirmacaoSenhaPlaceholder {
            get {
                return ResourceManager.GetString("UsuarioConfirmacaoSenhaPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o e-mail do usuário..
        /// </summary>
        public static string UsuarioEmailPlaceholder {
            get {
                return ResourceManager.GetString("UsuarioEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a senha do usuário..
        /// </summary>
        public static string UsuarioSenhaPlaceholder {
            get {
                return ResourceManager.GetString("UsuarioSenhaPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores Gastos pelo Candidato.
        /// </summary>
        public static string ValoresGastosCandidato {
            get {
                return ResourceManager.GetString("ValoresGastosCandidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores Gastos por Tipo de Ocorrência.
        /// </summary>
        public static string ValoresGastosTipoOcorrencia {
            get {
                return ResourceManager.GetString("ValoresGastosTipoOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        public static string Visualizar {
            get {
                return ResourceManager.GetString("Visualizar", resourceCulture);
            }
        }
    }
}
