//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPVR.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPVR.WebApp.Resources.ValidationErrorMessage", typeof(ValidationErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo importado com a lista dos candidatos não possui o formato esperado..
        /// </summary>
        internal static string ArquivoImportacaoCandidatosInvalidFormat {
            get {
                return ResourceManager.GetString("ArquivoImportacaoCandidatosInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Descrição da Unidade Eleitoral da Eleição à qual o Candidato está participando deve ter entre 1 e 255 caracteres..
        /// </summary>
        internal static string CandidatoDescricaoUnidadeEleitoralInvalidLength {
            get {
                return ResourceManager.GetString("CandidatoDescricaoUnidadeEleitoralInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do candidato deve ter no máximo 100 caracteres..
        /// </summary>
        internal static string CandidatoNomeInvalidLength {
            get {
                return ResourceManager.GetString("CandidatoNomeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do candidato não pode ser nulo..
        /// </summary>
        internal static string CandidatoNomeNotNull {
            get {
                return ResourceManager.GetString("CandidatoNomeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da urna do candidato deve ter no máximo 60 caracteres..
        /// </summary>
        internal static string CandidatoNomeUrnaInvalidLength {
            get {
                return ResourceManager.GetString("CandidatoNomeUrnaInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da urna do candidato não pode ser nulo..
        /// </summary>
        internal static string CandidatoNomeUrnaNotNull {
            get {
                return ResourceManager.GetString("CandidatoNomeUrnaNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Deputado Estadual não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralDeputadoEstadualInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralDeputadoEstadualInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Deputado Federal não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralDeputadoFederalInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralDeputadoFederalInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Governador não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralGovernadorInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralGovernadorInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Prefeito não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralPrefeitoInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralPrefeitoInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Presidência não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralPresidenteInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralPresidenteInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Senador não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralSenadorInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralSenadorInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número Eleitoral do Candidato à Vereador não é válido..
        /// </summary>
        internal static string CandidatoNumeroEleitoralVereadorInvalidRange {
            get {
                return ResourceManager.GetString("CandidatoNumeroEleitoralVereadorInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Sigla da Unidade Eleitoral da Eleição à qual o Candidato está participando deve ter entre 1 e 60 caracteres..
        /// </summary>
        internal static string CandidatoSiglaUnidadeEleitoralInvalidLength {
            get {
                return ResourceManager.GetString("CandidatoSiglaUnidadeEleitoralInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Sigla da Unidade da Federação da Eleição à qual o Candidato está participando não existe..
        /// </summary>
        internal static string CandidatoSiglaUnidadeFederacaoInvalidValue {
            get {
                return ResourceManager.GetString("CandidatoSiglaUnidadeFederacaoInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Descrição do Cargo Eletivo deve ter entre 1 e 255 caracteres..
        /// </summary>
        internal static string CargoEletivoDescricaoInvalidLength {
            get {
                return ResourceManager.GetString("CargoEletivoDescricaoInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Cargo Eletivo deve ter entre 1 e 30 caracteres..
        /// </summary>
        internal static string CargoEletivoNomeInvalidLength {
            get {
                return ResourceManager.GetString("CargoEletivoNomeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Cargo Letivo não pode ser nulo..
        /// </summary>
        internal static string CargoEletivoNomeNotNull {
            get {
                return ResourceManager.GetString("CargoEletivoNomeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da eleição deve ter entre 1 e 100 caracteres..
        /// </summary>
        internal static string EleicaoDescricaoInvalidLength {
            get {
                return ResourceManager.GetString("EleicaoDescricaoInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da eleição não pode ser nula..
        /// </summary>
        internal static string EleicaoDescricaoNotNull {
            get {
                return ResourceManager.GetString("EleicaoDescricaoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do Bairro deve ter entre 1 e 60 caracteres..
        /// </summary>
        internal static string EnderecoBairroInvalidLength {
            get {
                return ResourceManager.GetString("EnderecoBairroInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP informado não é válido..
        /// </summary>
        internal static string EnderecoCEPInvalidLength {
            get {
                return ResourceManager.GetString("EnderecoCEPInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome da Cidade deve ter entre 1 e 60 caracteres..
        /// </summary>
        internal static string EnderecoCidadeInvalidLength {
            get {
                return ResourceManager.GetString("EnderecoCidadeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Estado informado não existe..
        /// </summary>
        internal static string EnderecoEstadoInvalidValue {
            get {
                return ResourceManager.GetString("EnderecoEstadoInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Endereço Formatado deve ter entre 1 e 255 caracteres..
        /// </summary>
        internal static string EnderecoFormatadoInvalidLength {
            get {
                return ResourceManager.GetString("EnderecoFormatadoInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Descrição do Espectro Político deve ter no máximo 255 caracteres..
        /// </summary>
        internal static string EspectroPoliticoDescricaoInvalidLength {
            get {
                return ResourceManager.GetString("EspectroPoliticoDescricaoInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do espectro político deve ter entre 1 e 30 caracteres..
        /// </summary>
        internal static string EspectroPoliticoNomeInvalidLength {
            get {
                return ResourceManager.GetString("EspectroPoliticoNomeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do espectro político não pode ser nulo..
        /// </summary>
        internal static string EspectroPoliticoNomeNotNull {
            get {
                return ResourceManager.GetString("EspectroPoliticoNomeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A foto não possui as informações de geolocalização..
        /// </summary>
        internal static string ExifTagsGeolocationNull {
            get {
                return ResourceManager.GetString("ExifTagsGeolocationNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da ideologia deve ter entre 1 e 30 caracteres..
        /// </summary>
        internal static string IdeologiaNomeInvalidLength {
            get {
                return ResourceManager.GetString("IdeologiaNomeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma ideologia cadastrada com este nome, informe outro..
        /// </summary>
        internal static string IdeologiaNomeJaCadastrado {
            get {
                return ResourceManager.GetString("IdeologiaNomeJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da ideologia não pode ser nulo..
        /// </summary>
        internal static string IdeologiaNomeNotNull {
            get {
                return ResourceManager.GetString("IdeologiaNomeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo informato não possui um formato válido. Os formatos de imagem aceitos pelo sistema são: &quot;.jpg&quot;, &quot;.jpge&quot; e &quot;.png&quot;..
        /// </summary>
        internal static string OcorrenciaFotoInvalidFormat {
            get {
                return ResourceManager.GetString("OcorrenciaFotoInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A foto deve ser selecionada..
        /// </summary>
        internal static string OcorrenciaFotoNotNull {
            get {
                return ResourceManager.GetString("OcorrenciaFotoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo da propaganda deve ser informado..
        /// </summary>
        internal static string OcorrenciaTipoPropagandaNotNull {
            get {
                return ResourceManager.GetString("OcorrenciaTipoPropagandaNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O espectro político informado não existe..
        /// </summary>
        internal static string PartidoEspectroPoliticoInvalidValue {
            get {
                return ResourceManager.GetString("PartidoEspectroPoliticoInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do partido deve ter entre 1 e 60 caracteres..
        /// </summary>
        internal static string PartidoNomeInvalidLength {
            get {
                return ResourceManager.GetString("PartidoNomeInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do partido não pode ser nulo..
        /// </summary>
        internal static string PartidoNomeNotNull {
            get {
                return ResourceManager.GetString("PartidoNomeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número eleitoral do partido não é válido..
        /// </summary>
        internal static string PartidoNumeroEleitoralInvalidRange {
            get {
                return ResourceManager.GetString("PartidoNumeroEleitoralInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número eleitoral do partido não pode ser nulo..
        /// </summary>
        internal static string PartidoNumeroEleitoralNotNull {
            get {
                return ResourceManager.GetString("PartidoNumeroEleitoralNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sigla do partido deve ter entre 1 e 10 caracteres..
        /// </summary>
        internal static string PartidoSiglaInvalidLength {
            get {
                return ResourceManager.GetString("PartidoSiglaInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sigla do partido não pode ser nula..
        /// </summary>
        internal static string PartidoSiglaNotNull {
            get {
                return ResourceManager.GetString("PartidoSiglaNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do tipo da propaganda deve ter entre 1 e 30 caracteres..
        /// </summary>
        internal static string TipoPropagandaDescricaoInvalidLength {
            get {
                return ResourceManager.GetString("TipoPropagandaDescricaoInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do tipo da propaganda não pode ser nula..
        /// </summary>
        internal static string TipoPropagandaDescricaoNotNull {
            get {
                return ResourceManager.GetString("TipoPropagandaDescricaoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor médio do tipo da propaganda deve ser maior do que zero..
        /// </summary>
        internal static string TipoPropagandaValorMedioInvalidValue {
            get {
                return ResourceManager.GetString("TipoPropagandaValorMedioInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail não pode ser nulo..
        /// </summary>
        internal static string UsuarioEmailNotNull {
            get {
                return ResourceManager.GetString("UsuarioEmailNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha e a confirmação da senha não coincidem..
        /// </summary>
        internal static string UsuarioSenhaCompareSenhaConfirmacao {
            get {
                return ResourceManager.GetString("UsuarioSenhaCompareSenhaConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter entre {2} e {1} caracteres..
        /// </summary>
        internal static string UsuarioSenhaMinimumLength {
            get {
                return ResourceManager.GetString("UsuarioSenhaMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode ser nula..
        /// </summary>
        internal static string UsuarioSenhaNotNull {
            get {
                return ResourceManager.GetString("UsuarioSenhaNotNull", resourceCulture);
            }
        }
    }
}
